<?php

// получить контактные данные по стране
function getContacts($country) {
    $contacts["es"] = array(
        "address"=>"Plaza de Canalejas, ".rand(1,30).", ".rand(15111,35999)." Madrid, Spain",
        "phone"=>"+34 912 ".rand(10,99)."-".rand(10,99)."-".rand(10,99)
    );
    $contacts["it"] = array(
        "address"=>"Via Alberto Pollio, ".rand(1,70).", ".rand(10111,35999)." Roma RM, Italy",
        "phone"=>"+39 06 ".rand(100,999)."-".rand(10,99)."-".rand(10,99)
    );
    $contacts["pl"] = array(
        "address"=>"Złota ".rand(1,70).", ".rand(1,70)."-".rand(100,300)." Warszawa, Poland",
        "phone"=>"+48 22 ".rand(100,999)."-".rand(10,99)."-".rand(10,99)
    );
    $contacts["ro"] = array(
        "address"=>"Calea Floreasca Nr. ".rand(1,300)."B, București, Romania",
        "phone"=>"+40 730 ".rand(100,999)." ".rand(100,999)
    );
    $contacts["hu"] = array(
        "address"=>"Budapest, Váci út ".rand(1,9)."-".rand(1,9).", ".rand(1000,3000)." Hungary",
        "phone"=>"+36 1 ".rand(100,999)."-".rand(10,99)."-".rand(10,99)
    );
    $contacts["el"] = array(
        "address"=>"Leof. Kifisias ".rand(1,60)."A, Marousi ".rand(1,300)." ".rand(1,90).", Greece",
        "phone"=>"+30 21 0".rand(100,999)." ".rand(1000,9999).""
    );
    $contacts["pt"] = array(
        "address"=>"Av. Eng. Duarte Pacheco n° ".rand(1000,9999).", ".rand(1000,9999)."-".rand(100,999)." Lisboa, Portugal",
        "phone"=>"+351 21 ".rand(100,999)." ".rand(1000,9999).""
    );
    $contacts["en"] = array(
        "address"=>rand(1,99)." James St, Covent Garden, London ".rand(1000,9999)." ".rand(100,999).", United Kingdom",
        "phone"=>"+44 20 ".rand(1000,9999)." ".rand(1000,9999)
    );
    $contacts["vi"] = array(
        "address"=>rand(1,99)."Lieu Giai, Cong Vi, Ba Đình, Hà Noi ".rand(100000,999999).", Vietnam",
        "phone"=>"+84 24 ".rand(1000,9999)." ".rand(1000,9999)
    );



    return $contacts[$country];

}

// получить случайный цвет на замену базовых цветов
function getColorScheme() {
    // салатовый
    // среднетёмный фон #96CD00
    // чуть темнее #7aa700
    // тёмный фон #003046
    $random_scheme[] = array(
        "#F99209",
        "#be5e03"
    );
    $random_scheme[] = array(
        "#73BE1D",
        "#558804"
    );
    $random_scheme[] = array(
        "#03b36c",
        "#008d55"
    );
    $random_scheme[] = array(
        "#059595",
        "#014747"
    );

    $random_scheme[] = array(
        "#4393D0",
        "#034475"
    );
    $random_scheme[] = array(
        "#1061A0",
        "#08910f"
    );
    $random_scheme[] = array(
        "#0799fa",
        "#33076c"
    );





    $random_scheme[] = array(
        "#834fe2",
        "#3030c9"
    );
    $random_scheme[] = array(
        "#3a068d",
        "#771b77"
    );
    $random_scheme[] = array(
        "#d939ee",
        "#5f51df"
    );


    $random_scheme[] = array(
        "#D352CD",
        "#350533"
    );
    $random_scheme[] = array(
        "#e65b9b",
        "#3B0627"
    );
    $random_scheme[] = array(
        "#df4878",
        "#fc7a00"
    );
    $random_scheme[] = array(
        "#fc724f",
        "#709118"
    );






    $random_scheme[] = array(
        "#ffa600",
        "#181818"
    );
    $random_scheme[] = array(
        "#c43885",
        "#250303"
    );
    $random_scheme[] = array(
        "#53515c",
        "#00bef8"
    );
    $random_scheme[] = array(
        "#1c3d2b",
        "#41bd30"
    );
    $random_scheme[] = array(
        "#3d223a",
        "#94b618"
    );
    $random_scheme[] = array(
        "#3d223a",
        "#a04f8c"
    );




    $random_scheme[] = array(
        "#615d94",
        "#f77022"
    );
    $random_scheme[] = array(
        "#736be2",
        "#362f79"
    );
    $random_scheme[] = array(
        "#f37ddf",
        "#0b0630"
    );
    $random_scheme[] = array(
        "#252125",
        "#00becc"
    );
    $random_scheme[] = array(
        "#252125",
        "#4ec218"
    );
    $random_scheme[] = array(
        "#1d1c1c",
        "#ff7373"
    );

    shuffle($random_scheme);
//     echo "<pre>";
// 	print_r($random_scheme);
// 	echo "</pre>";
// die;
    return $random_scheme[0];

}

// получить случайное название компании :array("name", "email")
function getCompanyName() {
    $namesArr = array (
        "Beautdeck",
        "Beautadil",
        "Charm Farming",
        "Beautpad",
        "Cosmetics Aristocrat",
        "Natural Flourish",
        "Nature Victoria",
        "Charm Phoenix",
        "Allure Rack",
        "Charm Sonic",
        "Charm Pop",
        "Beauty Exalted",
        "Nature Achilles",
        "Natureish",
        "Cosmeticsadil",
        "Cosmetics Panda",
        "Nature Stella",
        "Charm Nixon",
        "Nature Compound",
        "Beautadri",
        "Cosmetics Wellness",
        "Natural Bonjour",
        "Nature Beguile",
        "Cosmetics Stake",
        "Beauty Absolute",
        "Cosmeticshut",
        "Beauty Answer",
        "Beauty Aim",
        "Beauty Angel",
        "Cosmeticspad",
        "Beauty Ammo",
        "Beauty Ave",
        "Beauty Aver",
        "Beauty Avatar",
        "Charm Forward",
        "Beauty Agents",
        "Beauty Anything",
        "Beautorzo",
        "Beauty Archives",
        "Cosmeticsscape",
        "Allure Speed",
        "Natureonus",
        "Natureworks",
        "Beauty Arid",
        "Beauty Awry",
        "Beauty Awards",
        "Beauty Anytime",
        "Naturaholic",
        "Health Sweat",
        "Cosmeticsly",
        "Natural Lineage",
        "Cosmetics Fix",
        "Nature Collusion",
        "Fashion Dip",
        "Healthly",
        "Cosmeticswind",
        "Natural Desire",
        "Healthadora",
        "Ideal Electrify",
        "Natural Maximum",
        "Beauty Mode",
        "Fashzilla",
        "Fashion Cosmic",
        "Nature Dahlia",
        "Natureiva",
        "Nature Fathom",
        "Beautgenix",
        "Cosmeticsella",
        "Fashion Polished",
        "Natural Adore",
        "Ideal Origin",
        "Fashion Blossom",
        "Fashopolis",
        "Organic Kit",
        "Health Pink",
        "Idenetic",
        "Natural Bounce",
        "Fashion Haute",
        "Fashion Bio",
        "Fashion Health",
        "Natural Methodical",
        "Natural Sombre",
        "Cosmetics Opacity",
        "Fashion Visage",
        "Organic Galore",
        "Natureopolis",
        "Fashion Elixir",
        "Idezoid",
        "Naturlia",
        "Cosmetics Stella",
        "Charm Program",
        "Organic Axe",
        "Idewind",
        "Cosmetics Jazz",
        "Natural Yard",
        "Beautocity",
        "Health Sheeny",
        "Health Heritage",
        "Cosmeticsops",
        "Allure Scouts",
        "Organic Bulk",
        "Ideal Exalted",
        "Organic Elevate",
        "Natural Relieve",
        "Cosmetics Design",
        "Cosmetics Tale",
        "Beauty Baron",
        "Cosmetics Functional",
        "Fashlux",
        "Natural Tease",
        "Beauty Ayesha",
        "Naturecog",
        "Nature Revolution",
        "Allure Announce",
        "Organic Divide",
        "Cosmeticssio",
        "Charm Rapid",
        "Fashion Planned",
        "Cosmetics Crystal",
        "Natural Dynasty",
        "Natural Source",
        "Health Serenity",
        "Fashion Heaven",
        "Idelia",
        "Natural Concept",
        "Cosmetics Picturesque",
        "Cosmetics Guru",
        "Ideal Fed",
        "Charm Mill",
        "Allure Tinged",
        "Nature Rich",
        "Charm Tenant",
        "Nature Raven",
        "Ideal Artful",
        "Organadil",
        "Fashion Grace",
        "Natural Defy",
        "Fashion Conventional",
        "Ideal Prince",
        "Charm Crave",
        "Naturester",
        "Health Glamour",
        "Fashion Purist",
        "Fashjet",
        "Health Exotic",
        "Cosmeticsocity",
        "Fashgenix",
        "Fashion Brilliance",
        "Beauty Xerxes",
        "Idebea",
        "Ideegy",
        "Ideal Appeal",
        "Organworks",
        "Naturegenix",
        "Organic Boost",
        "Cosmetics Bliss",
        "Organic Flawless",
        "Fashion Adoring",
        "Organic Defy",
        "Natural Posh",
        "Cosmetics Capacity",
        "Natural Bay",
        "Nature Grow",
        "Nature Reign",
        "Allure Scat",
        "Fashnetic",
        "Natureya",
        "Cosmetics Intensive",
        "Organic Steep",
        "Cosmeticsex",
        "Natural Maze",
        "Charm Amity",
        "Naturnetic",
        "Beautnetic",
        "Allure Pure",
        "Ideal Captain",
        "Naturish",
        "Orgando",
        "Naturbia",
        "Health Opacity",
        "Fashion Streamlined",
        "Nature Queen",
        "Natural Warmth",
        "Charm Versatile",
        "Allure Foster",
        "Charm Fix",
        "Cosmeticszoid",
        "Beauty Duke",
        "Beauty FX",
        "Ideal Story",
        "Ideal Grande",
        "Charm Obsession",
        "Organic Galvanic",
        "Nature Valley",
        "Beauty Wholesome",
        "Organic Divine",
        "Fashion Aspasia",
        "Allure Spur",
        "Allure Heritage",
        "Cosmetics Execute",
        "Charm Kart",
        "Natural Donna",
        "Natural Natural",
        "Beautlada",
        "Beauty Lacey",
        "Charm Broker",
        "Allure Box",
        "Allure Boho",
        "Beauty Split",
        "Cosmeticsdo",
        "Natural Exalted",
        "Natural Opulent",
        "Beauty Feast",
        "Beautporium",
        "Beautgenix",
        "Beauthut",
        "Cosmetics Dame",
        "Cosmetics Bash",
        "Cosmetics Aphrodite",
        "Beauty Guide",
        "Natural Vibe",
        "Cosmeticsology",
        "Beauty Shine",
        "Beauty Aqua",
        "Health First",
        "Nature Elevated",
        "Beautzilla",
        "Fashion Azraa",
        "Natural Olympia",
        "Natural Soul",
        "Charm Control",
        "Natural Bulk",
        "Cosmetics Fury",
        "Natural Balanced",
        "Cosmetics Easy",
        "Ideal Femme",
        "Natural Aladdin",
        "Organic Empress",
        "Allure Point",
        "Ideal Accentuate",
        "Cosmetics Body",
        "Naturlytical",
        "Health Equipped",
        "Beauty Swag",
        "Cosmeticsella",
        "Fashion Gaia",
        "Natural Mikado",
        "Nature Skill",
        "Beautistic",
        "Organic Ville",
        "Organic Sin",
        "Nature Mighty",
        "Nature Herbed",
        "Organic Sombre",
        "Fashcog",
        "Natural Sky",
        "Ideal Ameli",
        "Organfluent",
        "Fashex",
        "Natural Aroma",
        "Ideal Cosmic",
        "Beauty Prominent",
        "Charm Collar",
        "Fashion Grace",
        "Charm Posh",
        "Health Delilah",
        "Charm Taste",
        "Nature Insight",
        "Natural First Down",
        "Cosmeticswind",
        "Allure Master",
        "Beautadil",
        "Charm Galore",
        "Fashion Boost",
        "Organic Artful",
        "Idelance",
        "Organbes",
        "Natural Jaded",
        "Beautology",
        "Charm Supreme",
        "Cosmetics Void",
        "Fashion Ample",
        "Nature Collusion",
        "Fashion Purr",
        "Ideal Foxy",
        "Health Remedy",
        "Charm Fathom",
        "Naturesio",
        "Fashion Flip",
        "Idelia",
        "Ideal Bigger",
        "Allure Blueprint",
        "Allure Kids",
        "Health Parade",
        "Naturepad",
        "Organic Blended",
        "Charm Iconic",
        "Natural Radiance",
        "Allure Relic",
        "Nature Phoenix",
        "Healthlaza",
        "Charm Leaders",
        "Natural Fox",
        "Beauty Baked",
        "Ideal Lavish",
        "Natural Loud",
        "Charm Frisson",
        "Naturlada",
        "Natural Symmetry",
        "Ideal Flattering",
        "Organbia",
        "Charm Toolbox",
        "Fashable",
        "Health Jazz",
        "Natural Clinical",
        "Health Wholesome",
        "Ideal Blend",
        "Health Start",
        "Charm Fauna",
        "Organic Micro",
        "Natural Goodness",
        "Charm Heritage",
        "Charm Splendor",
        "Health Enlivening",
        "Health Kick",
        "Charm Dawn",
        "Natureocity",
        "Cosmetics Lucha",
        "Nature Smiling",
        "Healthara",
        "Organic Contact",
        "Ideal Swank",
        "Natureadora",
        "Cosmetics Lustrous",
        "Ideal Authentic",
        "Fashn",
        "Natural Appeal",
        "Allure Qualified",
        "Cosmetics Basics",
        "Naturenetic",
        "Organic Rediscover",
        "Beautscape",
        "Allure Unforgettable",
        "Natural Start",
        "Health Blend",
        "Ideaholic",
        "Charm Cheer",
        "Natural Exercise",
        "Fashion Silk",
        "Organic Affluence",
        "Health Majesty",
        "Cosmetics A+",
        "Charm Shine",
        "Natural Silhouette",
        "Natural Blend",
        "Cosmetics Order",
        "Beauty Jaded",
        "Beauty Earth",
        "Organic Palace",
        "Ideal Soul",
        "Organic Chow",
        "Organic Hercules",
        "Organiva",
        "Allure Drift",
        "Healthlux",
        "Allure Don",
        "Allure Velocity",
        "Cosmeticsry",
        "Nature Sheer",
        "Ideal Relieve",
        "Charm Hood",
        "Organic Fetching",
        "Cosmetics Scrumptious",
        "Cosmetics Sharpen",
        "Organic Place",
        "Fashion Nourish",
        "Cosmeticsbes",
        "Nature Salve",
        "Ideal Colorist",
        "Natural Aviator",
        "Cosmetics Aerobic",
        "Natural A-Line",
        "Beauty Exhibit",
        "Nature Grande",
        "Organsy",
        "Ideal Run",
        "Nature Fix",
        "Naturtastic",
        "Health Lasting",
        "Naturarc",
        "Natural Vape",
        "Allure Bonita",
        "Fashion Feast",
        "Cosmetics Galore",
        "Fashaholic",
        "Naturiva",
        "Cosmeticsx",
        "Nature Sugar",
        "Allure Tingle",
        "Naturorama",
        "Fashion Parade",
        "Beauty First",
        "Health Embrace",
        "Natural Sight",
        "Cosmetics Cave",
        "Natural Forage",
        "Health Simply",
        "Beauty Wagon",
        "Healthsy",
        "Natural TInted",
        "Natural Potential",
        "Cosmeticshut",
        "Natural Autumn",
        "Cosmeticsoont",
        "Natural Pix",
        "Organnest",
        "Organic Magma",
        "Charm Road",
        "Health Lifestyle",
        "Beauty Cycle",
        "Ideal Taper",
        "Fashion Ville",
        "Healthlada",
        "Orgando",
        "Beauty Idolize",
        "Beauty Swank",
        "Natural Splendorous",
        "Organic Wanderlust",
        "Cosmetics Hottie",
        "Fashque",
        "Cosmetics Live",
        "Nature Iron",
        "Organic Finesse",
        "Idelaza",
        "Beautbes",
        "Beauty Continental",
        "Health Purifying",
        "Organwind",
        "Organic Gains",
        "Allure Perspective",
        "Ideorama",
        "Allure Shenanigan",
        "Charm Excel",
        "Healthooze",
        "Idezoid",
        "Fashion Value",
        "Organic Affects",
        "Health Swanky",
        "Cosmetics Natural",
        "Cosmetics Bright",
        "Nature Owl",
        "Healthex",
        "Allure Delicious",
        "Organic Grow",
        "Cosmeticsjet",
        "Charm Strike",
        "Cosmeticscog",
        "Fashion Fascinating",
        "Fashlytical",
        "Ideal Canvas",
        "Fashx",
        "Organic All Star",
        "Nature Apollo",
        "Fashion Diced",
        "Natural Foundation",
        "Naturable",
        "Fashion H20",
        "Natural Better",
        "Health Beach",
        "Naturomatic",
        "Beauty Scrub",
        "Organic Skin",
        "Cosmetics Elan",
        "Natural Ablaze",
        "Fashion Classics",
        "Beauty Queen",
        "Cosmetics Raven",
        "Cosmeticsverse",
        "Cosmetics Nibble",
        "Cosmetics Botanica",
        "Beauty Choice",
        "Natural Pitch",
        "Cosmeticsarc",
        "Health Afterburner",
        "Ideaza",
        "Allure Treehouse",
        "Health Athens",
        "Health Service",
        "Ideprism",
        "Organic Classics",
        "Nature Soap",
        "Ideal Body",
        "Cosmetics Originals",
        "Allure Aroma",
        "Organic Grande",
        "Natural Show",
        "Beauty Alaska",
        "Natural Express",
        "Fashion Sheer",
        "Nature Samsonite",
        "Allure Insight",
        "Allure Lavish",
        "Charm Conveyance",
        "Nature Bite",
        "Natural Image",
        "Cosmetics Unforgettable",
        "Nature Image",
        "Nature Fascinating",
        "Charm Profits",
        "Fashify",
        "Allure Wire",
        "Allure Deluxe",
        "Allure Burnout",
        "Cosmetics Uptown",
        "Natural Embrace",
        "Natural Snug",
        "Ideal Xerxes",
        "Nature Bomb",
        "Health Roll",
        "Cosmetics Nutritious",
        "Cosmetics Hammer",
        "Natural Maximus",
        "Cosmetics Amber",
        "Organio",
        "Organic Galore",
        "Natural Vapor",
        "Beauty Hera",
        "Health Superior",
        "Charm Simple",
        "Cosmetics Scrub",
        "Cosmetics Clinic",
        "Charm Ally",
        "Natural Plants",
        "Allure Solution",
        "Allure Greener",
        "Organbea",
        "Ideal Rebalance",
        "Health Nurse",
        "Fashion Dynasty",
        "Nature Stallion",
        "Charm Mech",
        "Idearc",
        "Ideal Garnish",
        "Charm Trader",
        "Fashion Ninja",
        "Natural Chirp",
        "Healthaholic",
        "Ideio",
        "Natural Regency",
        "Nature Resort",
        "Health Clue",
        "Nature Focus",
        "Healtharo",
        "Nature Naturally",
        "Allure Painter",
        "Natural Glam",
        "Naturistic",
        "Charm Galactic",
        "Ideal Banish",
        "Fashion Frill",
        "Allure Reflex",
        "Health Closet",
        "Charm Go Time",
        "Cosmetics Crumb",
        "Charm Invest",
        "Ideex",
        "Beauty Accent",
        "Cosmeticsiva",
        "Beauty Elegant",
        "Cosmetics Bazaar",
        "Cosmetics Bio",
        "Health Grove",
        "Idehut",
        "Health Train",
        "Ideal Chic",
        "Allure Picks",
        "Health Exquisite",
        "Ideal Kitty",
        "Organlux",
        "Healthdeck",
        "Naturedeck",
        "Charm Eco",
        "Ideal Aura",
        "Natural Isolate",
        "Fashion Natural",
        "Fashion Duchess",
        "Ideal Sumo",
        "Fasharo",
        "Organic Wave",
        "Cosmetics Spotless",
        "Ideal Origin",
        "Natural Crown",
        "Health Modern",
        "Organic Street",
        "Natural Cuisine",
        "Nature Heat",
        "Natural Milli",
        "Fashion Venust",
        "Natural Invader",
        "Nature Ardor",
        "Naturearc",
        "Ideal Voluptuous",
        "Natural Yummy",
        "Natural Bison",
        "Fashion Sapphire",
        "Organlaza",
        "Beautjet",
        "Cosmetics League",
        "Charm Tera",
        "Nature Hilltop",
        "Organic Supply",
        "Allure Rhino",
        "Natural Ally",
        "Beauty Slice",
        "Allure Growth",
        "Charm Scout",
        "Beauty Romance",
        "Organic Knockout",
        "Cosmeticsops",
        "Organic Sharp",
        "Cosmeticsscape",
        "Nature Yummy",
        "Nature Hitch",
        "Organlytical",
        "Fashion Baked",
        "Cosmetics Clique",
        "Health Azraa",
        "Ideal Hot",
        "Healthadri",
        "Natureex",
        "Cosmetics Beguiling",
        "Naturscape",
        "Cosmetics Thor",
        "Nature Formula",
        "Beauty Diamond",
        "Natural Pearly",
        "Cosmetics Jacquard",
        "Natural Impact",
        "Health Tenor",
        "Beauty Coco",
        "Fashion Citron",
        "Cosmeticsistic",
        "Fashion Caliber",
        "Cosmeticsio",
        "Cosmetics Syndicate",
        "Health Stallion",
        "Beauty Food",
        "Cosmetics Slice",
        "Naturejet",
        "Charm Scope",
        "Cosmetics Grande",
        "Fashion Iron",
        "Organic Drip",
        "Organopedia",
        "Charm Espresso",
        "Ideal Outward",
        "Nature Stake",
        "Organomatic",
        "Nature Ritual",
        "Cosmetics Radiance",
        "Organic Hush",
        "Allure Strap",
        "Health Cave",
        "Natural Golden",
        "Naturlaza",
        "Cosmetics Stake",
        "Beauty Queens",
        "Natural Enrich",
        "Nature Crispy",
        "Natural Asset",
        "Idex",
        "Idearo",
        "Organic Better",
        "Beauty Bite",
        "Fashsio",
        "Fashzilla",
        "Cosmetics Venust",
        "Organic Gladiator",
        "Organtastic",
        "Allure Macro",
        "Charm Buff",
        "Charm Wick",
        "Fashion Grande",
        "Natural Glance",
        "Cosmetics Lust",
        "Fashion Blurred",
        "Fashion Outpost",
        "Natural Creator",
        "Cosmeticsque",
        "Allure Juice",
        "Health Snug",
        "Charm Squad",
        "Beauty Hotspot",
        "Organsio",
        "Beauty Ignite",
        "Beauty Elegance",
        "Fashion Honest",
        "Ideal Refresh",
        "Healthn",
        "Organic Olympic",
        "Allure Intelli",
        "Ideal Hardcore",
        "Health Symmetry",
        "Ideal Hustler",
        "Beautopolis",
        "Naturlance",
        "Cosmetics Renewing",
        "Cosmetics Don",
        "Health Cue",
        "Organic Atlantis",
        "Organify",
        "Charm Rest",
        "Beauty Hackel",
        "Cosmetics Nurse",
        "Cosmetics Herb",
        "Organaholic",
        "Ideella",
        "Allure Spring",
        "Nature Whole",
        "Natural Link",
        "Health Juggernaut",
        "Natural Bench",
        "Natural Matte",
        "Health Healthy",
        "Allure Guider",
        "Cosmetics Beyond",
        "Healthscape",
        "Allure Contributor",
        "Beautable",
        "Cosmeticslance",
        "Natural Ranger",
        "Health Dream",
        "Allure Care",
        "Ideal Craft",
        "Organic Element",
        "Allure Single",
        "Cosmeticssy",
        "Nature Ally",
        "Naturara",
        "Beauty Local",
        "Fashion Tulip",
        "Ideal Exquisite",
        "Fashion Khan",
        "Beautzoid",
        "Allure Gun",
        "Allure Joy",
        "Organocity",
        "Allure Export",
        "Cosmetics Rebalance",
        "Ideal Darling",
        "Ideal Closet",
        "Natural Nourish",
        "Natural Dusk",
        "Cosmetics Misguided",
        "Charm Imagine",
        "Beautlux",
        "Charm Crisp",
        "Fashion Herbed",
        "Allure Lilac",
        "Natural Paramount",
        "Nature Angelic",
        "Allure Royal",
        "Cosmetics Olympic",
        "Organic Decadent",
        "Organya",
        "Allure Cabal",
        "Naturebes",
        "Ideal Spicy",
        "Ideal Idol",
        "Organorama",
        "Nature Skin",
        "Allure Nirvana",
        "Nature Contact",
        "Ideal Delicacy",
        "Organgenics",
        "Charm Renew",
        "Health Livid",
        "Naturquipo",
        "Allure Metro",
        "Natural Supply",
        "Cosmetics Warm",
        "Charm Sure",
        "Ideal Aztec",
        "Health Anchor",
        "Natural Edulis",
        "Allure Goo",
        "Beautopedia",
        "Ideal Vine",
        "Beautiva",
        "Natural Hummingbird",
        "Organic Born",
        "Health Presto",
        "Organic Angelic",
        "Natural Action",
        "Beautoryx",
        "Nature Richness",
        "Fashion Invigorate",
        "Allure Stealth",
        "Health Glow",
        "Health Functional",
        "Health Fortify",
        "Ideal Hungry",
        "Health Hera",
        "Organic Majesty",
        "Organic Imperial",
        "Cosmetics Bounty",
        "Charm Grave",
        "Natural Femme",
        "Beauty Diva",
        "Organooze",
        "Health Matrix",
        "Allure Havoc",
        "Cosmetics Tenor",
        "Organic Grove",
        "Beauty Easy",
        "Beauty Iso",
        "Allure Warm",
        "Fashion Pure",
        "Beauty Classics",
        "Organic H20",
        "Beauty Fame",
        "Fashion Midnight",
        "Natural Bright",
        "Beauty Luxe",
        "Fashion Exert",
        "Nature Fame",
        "Fashion Syndicate",
        "Beautaholic",
        "Organic Avid",
        "Natureio",
        "Nature Crystal",
        "Beauty Blended",
        "Allure Chomp",
        "Nature Good",
        "Cosmeticslada",
        "Natural Cool",
        "Natural Blended",
        "Natural Mantle",
        "Cosmeticsdeck",
        "Nature Genius",
        "Allure Explosion",
        "Health Compound",
        "Fashion Guide",
        "Charm Real",
        "Charm Flowers",
        "Beautorama",
        "Cosmeticsster",
        "Natural Shack",
        "Fashion Void",
        "Cosmetics Fulfil",
        "Natural Insignia",
        "Naturverse",
        "Ideal Cave",
        "Ideal Gentle",
        "Nature Cycle",
        "Ideal Active",
        "Natural Velocity",
        "Charm Level",
        "Allure Jar",
        "Ideal Clan",
        "Beautaza",
        "Natural Unite",
        "Allure Instinct",
        "Natural Rugrat",
        "Cosmeticsgenix",
        "Beauty Place",
        "Health Viva",
        "Cosmetics Plan",
        "Beauty Serum",
        "Organic Swank",
        "Organnetic",
        "Natural Workshop",
        "Cosmetics Roll",
        "Naturenest",
        "Fashion Aid",
        "Health Ritzy",
        "Ideal Attractive",
        "Allure Kissable",
        "Cosmetics Fuel",
        "Allure Forge",
        "Allure Research",
        "Nature Protect",
        "Ideadora",
        "Health Bulk",
        "Fashion Jade",
        "Health Daisy",
        "Beautfluent",
        "Fashion Castaway",
        "Organic Barebone",
        "Organic Clever",
        "Naturocity",
        "Beauty Cleanse",
        "Allure Tera",
        "Organic Way",
        "Organic Progress",
        "Organic Strength",
        "Nature Bazaar",
        "Natural Feed",
        "Natural Ray",
        "Organic Glamour",
        "Natureopolis",
        "Nature Sweat",
        "Nature Dapper",
        "Fashion Thrive",
        "Health Skill",
        "Health Erase",
        "Allure Plus",
        "Beauty Wish",
        "Health Stake",
        "Organic Nurture",
        "Natural Rider",
        "Natural Tour",
        "Beautarc",
        "Naturx",
        "Organic Village",
        "Nature Finesse",
        "Fashion Remarkable",
        "Nature Balaclava",
        "Beauty Dine",
        "Natural Swank",
        "Natural Wheat",
        "Health Threads",
        "Fashion Closet",
        "Healthocity",
        "Naturops",
        "Allure Mountain",
        "Cosmeticssio",
        "Natural Tinged",
        "Beauty Eager",
        "Organjet",
        "Charm Picture",
        "Cosmetics Rebel",
        "Ideal Tinged",
        "Natural Mink",
        "Naturwind",
        "Naturadri",
        "Health Autumn",
        "Ideal Intensive",
        "Nature Bro",
        "Cosmeticsaro",
        "Naturebea",
        "Organic Boulder",
        "Natural Naturo",
        "Ideal Beyond",
        "Cosmeticsnetic",
        "Organadri",
        "Healthfluent",
        "Beautbea",
        "Fashion Brawn",
        "Nature Clue",
        "Charm Freaks",
        "Natureable",
        "Ideal Elevated",
        "Ideal Grove",
        "Allure Justice",
        "Cosmetics Bod",
        "Organado",
        "Health Cleanse",
        "Fashion Organica",
        "Fashion FX",
        "Allure Dhara",
        "Natural Stunner",
        "Nature Affinity",
        "Organic Sculpt",
        "Natural Atlantic",
        "Organic Vibrance",
        "Fashion Run",
        "Fashion Design",
        "Natural Grander",
        "Healthoryx",
        "Organic Mode",
        "Naturry",
        "Nature Hatchel",
        "Charm Chaos",
        "Organadora",
        "Organic Divine",
        "Cosmetics Purity",
        "Allure Digital",
        "Health Factory",
        "Charm Graceful",
        "Fashion Forage",
        "Charm Budget",
        "Charm Eclipse",
        "Health Rakish",
        "Fashion Legion",
        "Fashion Gun",
        "Natural Taking",
        "Fashion Spruce",
        "Nature Feast",
        "Fasharc",
        "Natural Paw",
        "Fashion Look",
        "Health Effect",
        "Healthopolis",
        "Fashion Clan",
        "Ideooze",
        "Nature Pathway",
        "Allure Image",
        "Health Harmonious",
        "Nature Dip",
        "Ideal Encore",
        "Fashion Authentic",
        "Cosmetics Wisdom",
        "Beauty Dynasty",
        "Ideal Blossom",
        "Charm Direct",
        "Natural Dreamy",
        "Cosmetics Stitch",
        "Charm Stack",
        "Beauty Samsonite",
        "Fashbes",
        "Ideal Dapper",
        "Beautaro",
        "Nature Madras",
        "Natureara",
        "Fashya",
        "Ideal Giant",
        "Charm Handy",
        "Beauty Wellbeing",
        "Charm Rapid",
        "Beauty Ora",
        "Cosmetics Snappy",
        "Allure Buddies",
        "Natural Barn",
        "Nature Glam",
        "Nature Hazel",
        "Natural Lotus",
        "Charm Elegance",
        "Natureopedia",
        "Ideal Essentials",
        "Allure Stack",
        "Cosmetics Tempting",
        "Natural Fresh",
        "Allure Aspire",
        "Natural Inspire",
        "Organarc",
        "Natural Spectator",
        "Organporium",
        "Organic Wayfarer",
        "Ideal Eternal",
        "Natural Shield",
        "Organic Queens",
        "Natural Drove",
        "Health Fresh",
        "Natural Garment",
        "Cosmetics Luxury",
        "Cosmetics Resort",
        "Naturadil",
        "Natural Mite",
        "Natureporium",
        "Natural Bytes",
        "Organic Velocity",
        "Natural Morning",
        "Cosmetics Style",
        "Nature Coastal",
        "Naturbes",
        "Natural Suburbia",
        "Nature Fad",
        "Allure Contact",
        "Nature Tale",
        "Allure Support",
        "Charm Lotus",
        "Natural Electrify",
        "Charm Searcher",
        "Naturzen",
        "Organic Snug",
        "Charm Lab",
        "Charm Apex",
        "Cosmetics Flaunt",
        "Health Spotless",
        "Beautish",
        "Organic Organic",
        "Natural Line",
        "Nature Deluxe",
        "Natural Ignite",
        "Fashion Exalted",
        "Cosmetics Repair",
        "Cosmetics Evermore",
        "Beauty Rakish",
        "Charm Space",
        "Cosmetics Faille",
        "Nature Road",
        "Natureado",
        "Organic Energy",
        "Organic Nip",
        "Cosmetics Knockout",
        "Allure Streams",
        "Organic Artistry",
        "Natural Delicacy",
        "Ideal Enviable",
        "Beauty Health",
        "Ideal Dogma",
        "Fashion Figure",
        "Health Fountain",
        "Charm Slue",
        "Natural Bug",
        "Charm Blurred",
        "Natural Superior",
        "Natural Roll",
        "Natural Stitch",
        "Fashion Strange",
        "Allure Myriad",
        "Fashion Comfort",
        "Natural Alliance",
        "Cosmetics Glance",
        "Health Cuts",
        "Health Profuse",
        "Cosmetics Spot",
        "Ideal Everything",
        "Allure Embrace",
        "Ideal Binge",
        "Natural Raw",
        "Ideal Knockout",
        "Charm Buddy",
        "Healthado",
        "Natural Guided",
        "Ideal Wellness",
        "Beauty Luminescent",
        "Naturfluent",
        "Naturegenics",
        "Allure Sharanam",
        "Natural Discussion",
        "Nature Plush",
        "Fashion Alpha",
        "Nature Public",
        "Naturster",
        "Organic Complete",
        "Beauty Streamlined",
        "Naturehut",
        "Nature Hideout",
        "Natural Prana",
        "Naturecog",
        "Naturesy",
        "Allure Armour",
        "Nature Nutrient",
        "Cosmetics Effect",
        "Cosmetics Magnificence",
        "Allure Flow",
        "Allure Savor",
        "Charm Milli",
        "Beauty Frill",
        "Nature Sumo",
        "Natural Ajax",
        "Natural Bang",
        "Beauty Isolate",
        "Allure Progress",
        "Cosmetics Closet",
        "Cosmetics Dashing",
        "Allure Knock",
        "Beauty Shelter",
        "Natural Sage",
        "Natural Spices",
        "Beauty Agile",
        "Beauty Ave",
        "Charm Skeptic",
        "Allure Barista",
        "Beauty Bargains",
        "Beauty Asset",
        "Charm Pacific",
        "Beauty About",
        "Beauty Active",
        "Charm Asset",
        "Cosmeticsorzo",
        "Charm Athena",
        "Allure Confections",
        "Beauty Aware",
        "Beauty Absolute",
        "Beauty Beast",
        "Charm Kickstart",
        "Beauty Action",
        "Charm Unit",
        "Beauty Archive",
        "Beauty Alliance",
        "Charm Drip",
        "Charm Stonemason",
        "Beauty Olympia",
        "Allure Aristocrat",
        "Cosmetics Sizzle",
        "Fashion Muscle",
        "Health Comply",
        "Organic Venus",
        "Fashomatic",
        "Ideal Carte",
        "Health Counter",
        "Cosmetics Flatter",
        "Allure Boss",
        "Cosmetics Wholesome",
        "Charm Anatomy",
        "Organoryx",
        "Natural Pantry",
        "Cosmeticsify",
        "Nature Define",
        "Health Nifty",
        "Health Pegasus",
        "Health Wellbeing",
        "Beautio",
        "Nature Refresh",
        "Natural Stream",
        "Cosmetics Gladiator",
        "Allure Robe",
        "Charm Fortify",
        "Organic Harp",
        "Natural Dub",
        "Nature Made",
        "Beautdeck",
        "Health Cut",
        "Cosmetics Hera",
        "Beautops",
        "Nature Encore",
        "Fashlada",
        "Ideal Tempean",
        "Organic Goodness",
        "Cosmetics Detox",
        "Organic A+",
        "Allure Deck",
        "Natural Clever",
        "Nature Ethereal",
        "Natural Grabber",
        "Cosmetics Support",
        "Natural Eclipse",
        "Organic Outward",
        "Ideya",
        "Natural Morals",
        "Allure World",
        "Health Body",
        "Fashion Irresistible",
        "Health Thrive",
        "Fashion Affluence",
        "Cosmetics Antidote",
        "Naturn",
        "Naturjet",
        "Nature Enticing",
        "Beauty Mindful",
        "Charm Candy",
        "Health Insignia",
        "Beautado",
        "Naturado",
        "Health Matte",
        "Allure Squared",
        "Natural Chic",
        "Health Become",
        "Fashion Care",
        "Charm Transition",
        "Naturzoid",
        "Cosmetics People",
        "Nature Dandy",
        "Fashooze",
        "Idebia",
        "Health Secret",
        "Cosmetics Guard",
        "Organic Bewitch",
        "Natural Prima",
        "Health Vigor",
        "Idejet",
        "Fashhut",
        "Charm Throttle",
        "Fashish",
        "Health Basics",
        "Nature Pure",
        "Natural Elevated",
        "Natural Spur",
        "Beauty Bay",
        "Natural Shake",
        "Idebes",
        "Fashion Balance",
        "Cosmetics Vanilla",
        "Naturoryx",
        "Allure Lance",
        "Health Haven",
        "Fashion Ajax",
        "Charm Fast Break",
        "Ideal Stake",
        "Fashion Goo",
        "Beauttastic",
        "Natural Motivate",
        "Nature Fuel",
        "Health Alluring",
        "Allure Resolve",
        "Organic Motion",
        "Cosmetics Cut",
        "Charm Attitude",
        "Beauty Craft",
        "Organprism",
        "Cosmetics Utopia",
        "Organic Remarkable",
        "Naturbia",
        "Health League",
        "Allure Namaste",
        "Cosmetics Ray",
        "Health Iso",
        "Healthbea",
        "Organic Exercise",
        "Natural Gene",
        "Natural Edge",
        "Health Dona",
        "Beauty Addiction",
        "Beauty Creed",
        "Beauty Desirable",
        "Fashion Styled",
        "Charm Aviator",
        "Natural Depot",
        "Cosmetics Steel",
        "Cosmetics Lion",
        "Nature 100",
        "Cosmetics Genius",
        "Charm Renegade",
        "Natural Hitch",
        "Charm Zita",
        "Cosmetics Hearty",
        "Cosmeticsadri",
        "Allure Recycle",
        "Nature Purr",
        "Charm Impulse",
        "Beautworks",
        "Cosmetics Boosts",
        "Nature Mesmeric",
        "Fashion Live",
        "Fashion Majestic",
        "Cosmetics Avid",
        "Natural Success",
        "Natural Hardcore",
        "Cosmetics Burn",
        "Ideal Tread",
        "Natural Inquire",
        "Naturen",
        "Cosmeticsadora",
        "Health Fantasy",
        "Allure Opacity",
        "Idepad",
        "Fashion Galore",
        "Healthegy",
        "Health Soap",
        "Charm Fortune",
        "Health Invincible",
        "Allure Legacy",
        "Organic Enchanting",
        "Health Flatter",
        "Charm Greens",
        "Nature Porcelain",
        "Organic Brightness",
        "Natural Celebration",
        "Cosmetics Flex",
        "Health Fiery",
        "Fashion Explosive",
        "Healthoont",
        "Ideal Parade",
        "Fashion Guard",
        "Cosmetics Affinity",
        "Allure Electrifying",
        "Charm Recorder",
        "Natural Haven",
        "Nature Pharaoh",
        "Fashion Desire",
        "Cosmetics Feast",
        "Nature Expert",
        "Organic Sportsman",
        "Natural Crowd",
        "Beauty Prestige",
        "Cosmeticsbia",
        "Health You",
        "Nature Delight",
        "Allure Bro",
        "Allure Antares",
        "Naturorzo",
        "Allure Mate",
        "Beauty Chakra",
        "Organic Laced",
        "Ideal Caramel",
        "Health Relieve",
        "Nature Strap",
        "Nature Soul",
        "Nature Axe",
        "Beauty Saint",
        "Healthaza",
        "Fashion Wonders",
        "Natural Bounty",
        "Fashion Action",
        "Cosmetics Haze",
        "Health Pigment",
        "Allure Willow",
        "Nature Ritzy",
        "Natural Laced",
        "Cosmetics Laced",
        "Beauty Effort",
        "Charm Kepler",
        "Ideal Natural",
        "Beauty Fury",
        "Cosmeticsoryx",
        "Charm Rainbow",
        "Organic Osiris",
        "Healthdo",
        "Allure Dominate",
        "Fashion Comply",
        "Ideal Harmony",
        "Cosmetics Functional",
        "Ideal Sage",
        "Ideal Ravish",
        "Charm Rogue",
        "Nature Electrifying",
        "Cosmetics Magnolia",
        "Charm Premiere",
        "Natural Begin",
        "Charm Creed",
        "Natural Planet",
        "Fashion Vine",
        "Natural Place",
        "Organzen",
        "Idelada",
        "Allure Crumble",
        "Nature Pulse",
        "Health Check",
        "Natural Infinity",
        "Fashion Genesis",
        "Health Dockside",
        "Nature Savor",
        "Ideal Visage",
        "Fashvio",
        "Ideal Garnet",
        "Nature Flourish",
        "Fashion Acclaimed",
        "Natural Cleopatra",
        "Nature Midnight",
        "Beautprism",
        "Natural Shining",
        "Ideal Achilles",
        "Fashion Allurement",
        "Natural Accentuate",
        "Organic Increase",
        "Allure Tribe",
        "Allure Merchant",
        "Fashion Lion",
        "Natural Extra",
        "Ideal Sunshine",
        "Natural Elegant",
        "Beauty Lounge",
        "Natural Beckon",
        "Ideomatic",
        "Health Safety",
        "Charm Artha",
        "Organic Gorgeous",
        "Naturprism",
        "Naturify",
        "Natural Riveting",
        "Beauty Midnight",
        "Fashadora",
        "Charm Move",
        "Organic Vigor",
        "Cosmeticsya",
        "Healthverse",
        "Ideoont",
        "Natural Essentials",
        "Nature Allurement",
        "Cosmetics Gentle",
        "Fashion Harmony",
        "Idester",
        "Nature Interval",
        "Beautry",
        "Nature Faille",
        "Beautegy",
        "Organology",
        "Nature Ineffable",
        "Fashion Cave",
        "Naturefluent",
        "Allure Consultant",
        "Cosmeticsquipo",
        "Nature Aphrodite",
        "Health Knight",
        "Fashion Avid",
        "Organic Kin",
        "Beauty Bismuth",
        "Natural Living",
        "Natural Peak",
        "Nature Society",
        "Health Zone",
        "Natureish",
        "Cosmetics Luxe",
        "Health Sheeny",
        "Nature Luminescent",
        "Ideal Desire",
        "Allure Ugly",
        "Allure Mason",
        "Organic Rhea",
        "Ideal Oil",
        "Fashion Robe",
        "Ideal Evolution",
        "Ideal Cool",
        "Ideal Regency",
        "Allure Sunny",
        "Charm Pay",
        "Nature Kin",
        "Health Attitude",
        "Organaza",
        "Beautverse",
        "Natural Intrigue",
        "Cosmetics Harp",
        "Ideal Guide",
        "Beauty Velocity",
        "Fashion Defy",
        "Naturonus",
        "Beauty Glory",
        "Health Luminescent",
        "Organic Planned",
        "Health Regenerate",
        "Charm Deem",
        "Natureverse",
        "Beautnest",
        "Charm Propel",
        "Natureomatic",
        "Charm Joint",
        "Ideish",
        "Allure Wellness",
        "Natural Obey",
        "Fashion Coverage",
        "Beauty Blend",
        "Charm Command",
        "Natural Steep",
        "Natural Advocate",
        "Organops",
        "Organic Coastal",
        "Natural Younger",
        "Allure Discuss",
        "Fashion Finesse",
        "Fashion Born",
        "Charm Shotgun",
        "Natural Diana",
        "Ideal Haute",
        "Natural Zephyr",
        "Allure Catalyst",
        "Allure Confidence",
        "Organic Trend",
        "Charm Kingdom",
        "Allure Hiatus",
        "Ideal Salve",
        "Ideal Lion",
        "Charm Training",
        "Nature Vail",
        "Fashion Panda",
        "Beauty Invincible",
        "Health Esthetic",
        "Beauty Splash",
        "Healthify",
        "Allure Rise",
        "Ideal Intentions",
        "Cosmetics Sumo",
        "Ideal Fantasy",
        "Idesy",
        "Natural Tropical",
        "Nature Cookie",
        "Fashion Luxe",
        "Fashio",
        "Organic Iso",
        "Fashops",
        "Fashion Tog",
        "Ideal Fetching",
        "Cosmeticsium",
        "Beauty Yummy",
        "Naturelytical",
        "Beauty Paw",
        "Charm Current",
        "Fashion Genic",
        "Charm Condition",
        "Cosmetics AAA",
        "Fashion Soft",
        "Organdeck",
        "Charm Comely",
        "Beauty Brew",
        "Ideal Ranch",
        "Natural Spike",
        "Natural Festive",
        "Fashion Harmonious",
        "Charm Love",
        "Natural Source",
        "Allure Control",
        "Nature Bewitch",
        "Fashion Cuisine",
        "Fashion Pulse",
        "Cosmetics Protect",
        "Natural Step",
        "Beauty Welfare",
        "Fashion Part",
        "Organic Connection",
        "Fashopolis",
        "Beautque",
        "Organzoid",
        "Allure Equality",
        "Charm Boom",
        "Nature Athens",
        "Allure Symmetry",
        "Cosmetics Fab",
        "Natural Flair",
        "Beauty Fascination",
        "Ideal Dine",
        "Ideal Majestic",
        "Beautly",
        "Fashion Bash",
        "Cosmetics Monroe",
        "Natureya",
        "Health Ambrosial",
        "Ideal Bulk",
        "Ideal Factory",
        "Natureorzo",
        "Beauty Unforgettable",
        "Cosmetics Reverence",
        "Cosmetics Enlivening",
        "Beauty Chef",
        "Natural Body",
        "Cosmetics Stamina",
        "Beautocity",
        "Organic Ravish",
        "Allure Romance",
        "Nature Duke",
        "Health Execute",
        "Charm Domain",
        "Cosmetics Bulk",
        "Allure Workbench",
        "Health Care",
        "Health Serum",
        "Natureadil",
        "Nature Winsome",
        "Ideal World",
        "Health Alley",
        "Organic Victoria",
        "Allure Orbiter",
        "Beautzen",
        "Organic Beguiling",
        "Charm Embrace",
        "Ideal Captivate",
        "Natural Refresh",
        "Health Emerald",
        "Natural Elysium",
        "Organic Gaia",
        "Ideal Exemplary",
        "Allure Maker",
        "Fashzoid",
        "Charm Aro",
        "Nature Drape",
        "Beautsy",
        "Nature Super",
        "Natural Options",
        "Beauty Habit",
        "Organic Youth",
        "Beauty Boulevard",
        "Charm Sumo",
        "Ideal Butterfly",
        "Ideal Planned",
        "Beauty Lavish",
        "Natural Response",
        "Natural Juicy",
        "Natural Boho",
        "Cosmetics Examine",
        "Ideal Jasmine",
        "Fashion Infinite",
        "Charm Drag",
        "Organic Me",
        "Charm Resolve",
        "Fashion Super",
        "Fashion Ava",
        "Allure Circles",
        "Health Clinic",
        "Organic Flavor",
        "Fashlia",
        "Beauty All Star",
        "Organic Connect",
        "Organic Serenity",
        "Beauty Figure",
        "Natural Comparison",
        "Health Mantle",
        "Cosmetics Genic",
        "Beauty Delilah",
        "Nature Dashing",
        "Cosmetics Dandy",
        "Charm Pirates",
        "Allure Daily",
        "Beauty Sportsman",
        "Cosmetics Idol",
        "Beauty Refinement",
        "Charm Indy",
        "Natural Lust",
        "Natural Grow",
        "Fashtastic",
        "Ideonus",
        "Natural Intensive",
        "Charm Epic",
        "Ideadri",
        "Natural Flatter",
        "Fashion Mash",
        "Nature Desirable",
        "Health Heritage",
        "Natural Fix",
        "Organic Comely",
        "Charm Esthetic",
        "Charm Grounds",
        "Natural 100",
        "Natural Angel",
        "Fashion Equipped",
        "Allure Insane",
        "Natural Carte",
        "Natural Protein",
        "Fashion Calm",
        "Allure Pure",
        "Charm Junction",
        "Organic Free",
        "Health Prestige",
        "Health Choose",
        "Allure Centaur",
        "Ideal",
        "Cosmetics Blend",
        "Naturelia",
        "Fashion Heroine",
        "Natural Cleo",
        "Charm Exchange",
        "Allure Week",
        "Fashion Summer",
        "Cosmetics Iron",
        "Fashion Become",
        "Nature Pavement",
        "Nature Hammer",
        "Charm Helpline",
        "Allure Beaming",
        "Natural Planted",
        "Allure Dream",
        "Fashion Tease",
        "Allure Vice",
        "Healthtastic",
        "Charm Promotional",
        "Naturopolis",
        "Allure Circle",
        "Natural Ritual",
        "Charm Peachy",
        "Fashion Fab",
        "Natural Contour",
        "Cosmetics Applique",
        "Nature Opacity",
        "Cosmetics Beckon",
        "Charm Sweetheart",
        "Ideal Stamina",
        "Natural Ora",
        "Fashion Story",
        "Natural Nude",
        "Cosmetics Vail",
        "Allure Light",
        "Charm Diamond",
        "Charm Tailor",
        "Organic Support",
        "Fashnest",
        "Natural Unforgettable",
        "Fashion Instinct",
        "Fashion Sin",
        "Beauty H20",
        "Organic Cleopatra",
        "Nature Complete",
        "Natural Shotgun",
        "Health Idolize",
        "Cosmeticsorama",
        "Charm Upgrade",
        "Ideal Embrace",
        "Naturpad",
        "Charm Freedom",
        "Organic Happening",
        "Health Warrior",
        "Charm Oscar",
        "Nature Dude",
        "Charm Hopper",
        "Natural Luxuriate",
        "Ideal Bomb",
        "Allure Parade",
        "Health Splendour",
        "Health Enticing",
        "Beauty Spices",
        "Natural Butterfly",
        "Fashion Glory",
        "Allure Charming",
        "Nature Simple",
        "Cosmetics Bismuth",
        "Cosmetics Fine",
        "Healthry",
        "Cosmetics Coveted",
        "Organic Exhibit",
        "Nature Capri",
        "Fashion Lavish",
        "Natural Friends",
        "Ideal Obsession",
        "Cosmetics Passional",
        "Allure Tricks",
        "Charm Customs",
        "Beauty Repair",
        "Charm Rating",
        "Natural Boy",
        "Fashion Bison",
        "Beautx",
        "Fashion Hideout",
        "Charm System",
        "Ideal Attract",
        "Charm Joy",
        "Health Pure",
        "Health Nurture",
        "Cosmetics Amenity",
        "Ideegy",
        "Natural Hercules",
        "Natural Bewitch",
        "Charm Speed",
        "Organlance",
        "Beauty Macho",
        "Health Misguided",
        "Fashion Appetite",
        "Nature Above",
        "Charm Continuum",
        "Charm Shops",
        "Natural Stallion",
        "Natural Pamper",
        "Natural Fortitude",
        "Natural Push",
        "Organic Prestige",
        "Health Connoisseur",
        "Health Free",
        "Fashion Define",
        "Organic Monroe",
        "Idelytical",
        "Allure Snap",
        "Natural Heaven",
        "Organic Streamlined",
        "Health Hot",
        "Fashion Basics",
        "Charm Result",
        "Organistic",
        "Ideal Mane",
        "Organic Olympia",
        "Beauty Bulk",
        "Cosmetics Aviator",
        "Health Ablaze",
        "Health Luxuriant",
        "Health Dynasty",
        "Ideal Happening",
        "Organic Stitch",
        "Ideal Herb",
        "Fashion Mind",
        "Natural Freight",
        "Natural Olympic",
        "Natural Balance",
        "Fashion Lucious",
        "Organn",
        "Beauty Botanical",
        "Healthish",
        "Cosmetics Mikado",
        "Ideal Essence",
        "Beauty Mighty",
        "Charm Creative",
        "Natural Revolve",
        "Ideal Clio",
        "Allure Wave",
        "Organic Colorway",
        "Cosmetics Fresh",
        "Organic Fresh",
        "Cosmetics Runway",
        "Charm Ignite",
        "Natural Mudra",
        "Natural Sombre",
        "Fashara",
        "Cosmetics Luminescent",
        "Health Mind",
        "Organverse",
        "Organic Elegant",
        "Idezilla",
        "Organry",
        "Beauty Hustler",
        "Natural Haute",
        "Natural Juggernaut",
        "Fashion Treehouse",
        "Beautgenics",
        "Nature Admire",
        "Nature Amaze",
        "Nature Minty",
        "Healthnetic",
        "Ideal Boho",
        "Allure Giga",
        "Cosmeticszilla",
        "Cosmetics Sombre",
        "Natural Fine",
        "Fashion Bar",
        "Health Street",
        "Natural Crystal",
        "Charm Swell",
        "Health Image",
        "Allure Garden",
        "Natural Vital",
        "Natural Wish",
        "Beauty Stake",
        "Fashion Bear",
        "Organic Ignite",
        "Beautlia",
        "Nature Hot",
        "Natural Wage",
        "Charm Hatha",
        "Health Bewitch",
        "Allure Savasana",
        "Natural Diamond",
        "Allure Way",
        "Organvio",
        "Organic Radiance",
        "Fashion Paramount",
        "Naturbea",
        "Charm Shore",
        "Health Regent",
        "Allure Passion",
        "Naturetastic",
        "Natural Amber",
        "Ideal Sapphire",
        "Cosmetics Aspasia",
        "Ideal Viva",
        "Organopolis",
        "Natural Lily",
        "Beauty People",
        "Natural Figure",
        "Organic Prince",
        "Allure Joint",
        "Natural Flex",

    );
    shuffle($namesArr);
    // return $namesArr[0];
    return $company = array(
        "name"=>trim($namesArr[0]),
        "email"=>mb_strtolower(str_replace( " ", "-", trim($namesArr[0]))) . "@gmail.com"
    );
}





?>